name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to release (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # needed for tags

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Bump workspace versions and commit
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Bumping all workspaces to version $VERSION"
          yarn workspaces foreach -Av version $VERSION
          yarn update-samples
          git add .
          git commit -m "chore(release): bump version to v$VERSION" || echo "No changes to commit"
          git tag v$VERSION
          git push origin HEAD
          git push origin v$VERSION

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build & tests
        run: |
          cd tests && yarn clean && cd ..
          yarn clean
          yarn clean:all
          yarn build
          yarn test
          yarn test:samples

      - name: Configure npm authentication
        run: |
          yarn config set npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}

      - name: Publish workspaces to npm
        run: yarn workspaces foreach --all --no-private -v npm publish --tolerate-republish
